application: whats-going-on-in
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /test.*
  script: gaeunit.py
  login: admin

- url: /_admin.*
  script: handlers/admin/main.py
  login: admin
  
- url: /.*
  script: handlers/public/main.py
