application: culcal
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /test.*
  script: testing/gaeunit.py

- url: /_admin.*
  script: handlers/admin/main.py
  login: admin
  
- url: .*
  script: main.py
